services:
  backend:
    build: Backend/.
    ports:
      - "5000:5000"  

  frontend:
    build: frontend/.
    ports:
      - "3000:3000" 

  postgres:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: establishment
    volumes:
      - ./db-backup/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres    