services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    volumes:
      - ./db-backup/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres
  backend:
    build: Backend/.
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/mydb?schema=public?connect_timeout=5000
      - JWT_SECRET = secret
    depends_on:
      - postgres

  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
    depends_on:
      - backend
